Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzas/urls.py
"""Defines URL patterns for pizzas."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Page showing all pizzas.
    path('pizzas/', views.pizzas, name='pizzas'),
    # Page showing an individual pizza.
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
]

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzas/models.py
from django.db import models

class Pizza(models.Model):
    """Represent a pizza that can be ordered from the pizzeria."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

class Topping(models.Model):
    """A topping that can be added to a pizza."""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def index(request):
    """The home page for Pizzeria."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Page showing all pizzas that are available."""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Page showing information about an individual pizza."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.all()

    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> - 
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>Welcome to the Pizzeria! We hope you'll find a pizza that you like. :)</p>
{% endblock content %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>Pizza: {{ pizza.name }}</p>

  <p>Toppings:</p>
  <ul>
    {% for topping in toppings %}
      <li>{{ topping.name }}</li>
    {% empty %}
      <li>There are no toppings on this pizza.</li>
    {% endfor %}
  </ul>
  
{% endblock content %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_18/ex_18_8_pizzeria_pages/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>Pizzas</p>

  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name }}</a>
      </li>
    {% empty %}
      <li>We don't currently have any pizzas available.</li>
    {% endfor %}
  </ul>

{% endblock content %}