Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
]

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page to view all blogs that have been created.
    path('blogs/', views.blogs, name='blogs'),
    # Page to view an individual blog, and all its posts.
    path('blog/<int:blog_id>/', views.blog, name='blog'),

    # Page for creating a new blog.
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for writing a new post.
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Page for editing an existing post.
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/accounts/models.py
from django.db import models

# Create your models here.

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    """Represents one person or organization's blog."""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the blog."""
        return self.name

class BlogPost(models.Model):
    """Represents an individual post."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=500)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representing the blog post."""
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return self.title

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/forms.py
from django import forms

from .models import Blog, BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'body']

        widgets = {'body': forms.Textarea(attrs={'cols': 80})}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm


def index(request):
    """The home page for Blog."""
    return render(request, 'blogs/index.html')

def blogs(request):
    """Page to view all blogs that have been newd."""
    blogs = Blog.objects.all()
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """Page to view an individual blog, and all its posts."""
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.all()

    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)

@login_required
def new_blog(request):
    """Page to new a new blog."""
    if request.method != 'POST':
        # No data submitted; new a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blogs')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)

@login_required
def new_post(request, blog_id):
    """Page to create a new post."""
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)

    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """Page to edit an existing post."""
    post = BlogPost.objects.get(id=post_id)
    blog = post.blog
    check_blog_owner(blog, request.user)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = BlogPostForm(instance=post)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)

    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

def check_blog_owner(blog, user):
    """Make sure the currently logged-in user owns the blog that's 
    being requested.

    Raise Http404 error if the user does not own the blog.
    """
    if blog.owner != user:
        raise Http404

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Learning Log</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blogs:index' %}">
          Blog Host</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:blogs' %}">
              Blogs</a></li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account-related links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}.
                </span></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                  Register</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                  Log in</a></li>
          {% endif %}

        </ul> <!-- End of account-related links -->

        {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-secondary btn-sm'>
              Log out</button>
          </form>
        {% endif %}

      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>{{ blog.name }}</h1>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'blogs:new_post' blog.id %}">Create a new post</a>
  </p>

{% for post in posts %}
    <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
      <h4 class="card-header">{{ post.title }}</h4>
      <div class="card-body">
        <!-- Card body with post body -->
        <p class="card-text">{{ post.body|linebreaks }}</p>
        <p class="text-end">{{ post.date_added|date:'M d, Y H:i' }}</p>
      </div>
      <div class="card-footer text-muted">
        <p class="text-end"><a href="{% url 'blogs:edit_post' post.id %}">
          edit post</a></p>
      </div>
    </div>
  {% empty %}
    <p>This blog does not have any posts yet.</p>
  {% endfor %}

{% endblock content %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>All Blogs</h1>
{% endblock page_header %}

{% block content %}

  <ul class="list-group border-bottom pb-2 mb-4">
    {% for blog in blogs %}
      <li class="list-group-item border-0">
        <a href="{% url 'blogs:blog' blog.id %}">
          {{ blog.name }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">No blogs have been created yet.</li>
    {% endfor %}
  </ul>

  <a href="{% url 'blogs:new_blog' %}">Start a new blog</a>

{% endblock content %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Edit post</h2>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.name }}</a></p>

  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Save changes" %}
  </form>

{% endblock content %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">Blog Host</h1>
      
      <p class="lead">Create your own blog, and share it with the world.</p>

      <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'accounts:register' %}">Register &raquo;</a>
    </div>
  </div>
{% endblock page_header %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Create a new blog.</h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'blogs:new_blog' %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Create blog" %}
  </form>

{% endblock content %}

Books/Python Crash Course/pcc_3e-main/solution_files/chapter_20/ex_20_2_stylish_blog/blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Create a new post.</h2>
{% endblock page_header %}

{% block content %}

  <p><a href="{% url 'blogs:blog' blog.id %}">{{ blog.name }}</a></p>

  <form action="{% url 'blogs:new_post' blog.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Create post" %}
  </form>

{% endblock content %}